### ISSUE TITLE
RC1 TODO

### ISSUE THREAD

**Issue by xhebox** [xhebox/noname-linux#4]
- [ ] nice to get a more friendly install tutorial, and a qemu image creater!
- [ ] all scripts using getopts
- [ ] clean my own config files in repo
      - [ ] filesystems
      - [ ] finit
      - [ ] dwm, slstatus
- [ ] an irc room if needed?

**Comment by xhebox** [comment]
list:
- [x] chromium
- [x] gtk2/3
- [x] atk
- [x] fcitx
- [x] gdk-pixbuf
- [x] librsvg
- [x] pango
- [x] gobject-introspection
- [x] gnome-common
